services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html
    depends_on:
      - caddy
      - db
      - redis
    networks:
      - backend
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "${APP_CPUS:?}"
          memory: "${APP_MEMORY:?}"

  caddy:
    image: caddy
    ports:
      - "${CADDY_PORT:?}:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src:/var/www/html
    restart: always
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "${CADDY_CPUS:?}"
          memory: "${CADDY_MEMORY:?}"

  redis:
    image: redis:latest
    restart: unless-stopped
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:?}"
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
    networks:
      - backend

  db:
    image: mysql
    restart: unless-stopped
    tty: true
    expose:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:?}"
      MYSQL_USER: "${MYSQL_USER:?}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?}"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: ${NETWORK_NAME:?}
