version: '3.8'

services:
  app:
    image: laravel-scalable-app:latest
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/var/www/html
    ports:
      - target: 80
        published: "${WEB_PORT:?}"
        protocol: tcp
        mode: ingress
    networks:
      - backend
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:?}"]
    volumes:
      - ./data/redis:/data
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  db:
    image: mysql
    tty: true
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:?}"
      MYSQL_USER: "${MYSQL_USER:?}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?}"
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  backend:
    driver: overlay
    attachable: true
    name: "laravel"
